### Numpy ndarray 활용

In [1]:
import numpy as np

##### 파이썬 리스트를 numpy의 ndarray로 변환

In [2]:
list1 = [1, 2, 3]
array1 = np.array(list1)
print("list1: ", list1, type(list1))
print("array1: ", array1, type(array1))

list1:  [1, 2, 3] <class 'list'>
array1:  [1 2 3] <class 'numpy.ndarray'>


##### ndarray의 형태와 차원

In [3]:
# 1차원
array1 = np.array([1, 2, 3])
print("array1 형태: ", array1.shape)
print("array1 차원: ", array1.ndim)
#2차원
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print("array1 형태: ", array2.shape)
print("array1 차원: ", array2.ndim)

array1 형태:  (3,)
array1 차원:  1
array1 형태:  (2, 3)
array1 차원:  2


##### astype()을 통한 타입 변환

In [4]:
array_ori = np.array([1, 2, 3])
array_float = array_ori.astype('float64')
print("정수에서 실수로 형 변환: ", array_float, array_float.dtype)

정수에서 실수로 형 변환:  [1. 2. 3.] float64


##### ndarray에서 axis기반의 연산함수 수행 

* axis는 행과 열이다. axis0 = 행 axis1 = 열

In [5]:
array2 = np.array([[1, 2, 3], [4, 5, 6]])

#  nparray에 있는 요소 전부의 합
print(array2.sum())
#행을 기준으로 합
print(array2.sum(axis=0))
#열을 기준으로 합
print(array2.sum(axis=1))

21
[5 7 9]
[ 6 15]


##### ndarray를 편리하게 생성하기(arange, zeros, ones)

In [6]:
#arange()
# 0부터 10개를 가지는 1차원 ndarray를 생성
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [7]:
#zeros()
#dtype을 명시하지 않으면 float형으로 초기화 된다.(ones()도 마찬가지)
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [8]:
#ones
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


##### ndarray의 shape을 변경하는 reshape()

In [9]:
array1 = np.arange(10)
array2 = array1.reshape(2, 5)
print("array2:\n", array2)
# array의 범위를 벗어나면 에러 발생

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


##### reshape() 인자에 -1을 대입하면 가변적인 축이 된다.

In [10]:
array1 = np.arange(10)
array2 = array1.reshape(-1, 5)
print("array2:\n", array2)

array3 = array1.reshape(5, -1)
print("array3:\n", array3)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


##### tip: reshape()는 (-1, 1), (-1,)형태가 자주 사용된다.

In [11]:
array1 = np.arange(10)
# 1차원 ndarray를 2차원 ndarray로 변환
array2 = array1.reshape(-1, 1)
print("array2:\n", array2)
# 2차원 ndarray를 1차원 ndarray로 변환
array3 = array1.reshape(-1,)
print("array3:\n", array3)

# 인자로 -1을 넣을 때는 하나의 축만 -1을 하여야 한다.

array2:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
array3:
 [0 1 2 3 4 5 6 7 8 9]


### ndarray의 데이터 세트 선택하기(인덱싱:indexing)

##### 특정 위치의 단일값 추출

In [12]:
# 1에서 9까지 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print("array1: ", array1)

# index 기준의 data를 추출
data = array1[2]
print(data)
print(type(data))
print("맨 뒤의 값: ", array1[-1], ", 맨 뒤에서 2번째 값: ", array1[-2])

array1:  [1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>
맨 뒤의 값:  9 , 맨 뒤에서 2번째 값:  8


In [13]:
# 값 재할당하기
array1[0] = 9
array1[-1] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [14]:
# 2차원 ndarray index활용
array1d = np.arange(start = 1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print("(row=0,col=0)", array2d[0, 0])
print("(row=1,col=2)", array2d[1, 2])
print("(row=2,col=1)", array2d[2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) 1
(row=1,col=2) 6
(row=2,col=1) 8


##### 슬라이싱(slicing)

In [15]:
array1 = np.arange(start = 1, stop = 10)
print(array1)
array2 = array1[0:3]
print(array2)
print(type(array2))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [16]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1[:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [17]:
array1 = np.arange(start = 1, stop = 10)

array4 = array1[:3]
print(array4)
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [18]:
array1 = np.arange(start = 1, stop = 10)
array2 = array1.reshape(3, 3)
print("array2:\n", array2)

print("array2[0:2, 0:2]\n", array2[0:2, 0:2])
print("array2[1:3, 0:3]\n", array2[1:3, 0:3])
print("array2[1:3, :]\n", array2[1:3, :])
print("array2[:, :]\n", array2[:, :])
print("array2[:2, 1:]\n", array2[:2, 1:])
print("array2[:2, 0]\n", array2[:2, 0])

array2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[0:2, 0:2]
 [[1 2]
 [4 5]]
array2[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[:2, 1:]
 [[2 3]
 [5 6]]
array2[:2, 0]
 [1 4]


##### 펜시 인덱싱(fancy indexing)

In [19]:
# 원하는 요소들만 모아 다른 배열을 생성 가능
array1 = np.arange(start = 1, stop = 10)
array2 = array1.reshape(3, 3)
print(array2)

array3 = array2[[0,1], 2]
print('array2[[0,1], 2] => ',array3.tolist())

array4 = array2[[0,2], 0:2]
print('array2[[0,2], 0:2] => ',array4.tolist())

array5 = array2[[0,1]]
print('array2[[0,1]] => ',array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[[0,1], 2] =>  [3, 6]
array2[[0,2], 0:2] =>  [[1, 2], [7, 8]]
array2[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


##### 불린 인덱싱(boolean indexing)

In [20]:
array1 = np.arange(start = 1, stop = 10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [21]:
print(array1 > 5)

var1 = array1 > 5
print("var1:",var1)
print(type(var1))

[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [22]:
# [ ] 안에 true에 해당하는 index데이터만 저장 
print(array1)
array3 = array1[array1 > 5]
print('array1 > 5 불린 인덱싱 결과 값 :', array3)

[1 2 3 4 5 6 7 8 9]
array1 > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [23]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [24]:
# ndarray의 요소를 index로 활용
indexes = np.array([5,6,7,8])
array4 = array1[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [25]:
array1 = np.arange(start = 1, stop = 10)
target = []

for i in range(0, 9):
    if array1[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


### 행렬의 정렬(sort(), argsort())
* argsort() : 정렬한 후 원본행렬의 index를 반환

In [26]:
org_array = np.array([ 3, 1, 9, 5]) 
print("원본 행렬: ", org_array)

# np.sort()로 정렬(원본은 그대로 있음) 
sort_array1 = np.sort(org_array)         
print ("np.sort() 호출 후 반환된 정렬 행렬: ", sort_array1) 
print("np.sort() 호출 후 원본 행렬: ", org_array)

# ndarray.sort( )로 정렬(원본이 변함)
sort_array2 = org_array.sort()
print("org_array.sort() 호출 후 반환된 행렬: ", sort_array2)
print("org_array.sort() 호출 후 원본 행렬: ", org_array)

원본 행렬:  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]


In [27]:
# 내림차순 정렬[::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print ("내림차순으로 정렬:", sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [28]:
array2d = np.array([[8, 12, 9], 
                   [7, 1, 3 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print("로우 방향으로 정렬:\n", sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print("컬럼 방향으로 정렬:\n", sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1  3]
 [ 8 12  9]]
컬럼 방향으로 정렬:
 [[ 8  9 12]
 [ 1  3  7]]


##### argsort()

In [29]:
org_array = np.array([ 3, 1, 9, 5]) 
print(np.sort(org_array))

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print("행렬 정렬 시 원본 행렬의 인덱스:", sort_indices)

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [30]:
org_array = np.array([ 3, 1, 9, 5]) 
print(np.sort(org_array)[::-1])

sort_indices_desc = np.argsort(org_array)[::-1]
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스:", sort_indices_desc)

[9 5 3 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


##### key-value 형태의 데이터를 argsort()를 이용하여 value정렬 후 key값을 정렬

In [31]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

# score_array의 정렬된 값에 해당하는 원본 행렬 위치 인덱스 반환하고 이를 이용하여 name_array에서 name값 정렬  
sort_indices = np.argsort(score_array)
print("sort indices:", sort_indices)

name_array_sort = name_array[sort_indices]

score_array_sort = score_array[sort_indices]
print(name_array_sort)
print(score_array_sort)

sort indices: [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
* 행렬 내적

In [32]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print("행렬 내적 결과:\n" , dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬 : 열과 행을 바꾼 행렬

In [33]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

transpose_mat_A = np.transpose(A)
transpose_mat_B = np.transpose(B)
print("A의 전치 행렬:\n", transpose_mat_A)
print("B의 전치 행렬:\n", transpose_mat_B)

A의 전치 행렬:
 [[1 3]
 [2 4]]
B의 전치 행렬:
 [[ 7  9 11]
 [ 8 10 12]]
